Resources:
  RedisSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        PasswordLength: 64
        IncludeSpace: false
        ExcludePunctuation: true
Outputs:
  SecretArn:
    Value: !Ref RedisSecret
    Export:
      Name: SecretArn