Parameters:
  VpcId:
    Type: String
  SubnetId:
    Type: String
Resources:
  DemoInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Demo Group"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
  DemoInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'
      InstanceType: "t3.micro"
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref DemoInstanceSecurityGroup